services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx/dev/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
      - app
    container_name: app_nginx

  db:
    image: mariadb:12.2.2
    restart: always
    volumes:
      - ./db_data/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_PORT}:3306
    container_name: app_database

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./public:/etc/webroot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    container_name: app_certbot

  memcached:
    image: memcached:1.6.41
    command:
      - --memory-limit=128
    container_name: app_cache

  app:
    build:
      context: .
      dockerfile: Docker/app/Dockerfile
    volumes:
      - ./:/var/www

    container_name: app_app
    depends_on:
      - db

networks:
  default:
    driver: bridge
