server {
    listen 80;
    server_name edwak97.ru www.edwak97.ru;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;

    root /var/www/public;

    ssl_certificate /var/www/certs/live/www.edwak97.ru/fullchain.pem;
    ssl_certificate_key /var/www/certs/live/www.edwak97.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNull:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
      try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
